/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppTopBar: typeof import('./components/AppTopBar.vue')['default']
    Clock: typeof import('./components/Clock.vue')['default']
    ExamList: typeof import('./components/ExamList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SubjectInfo: typeof import('./components/SubjectInfo.vue')['default']
    SvgIcon: typeof import('./components/SvgIcon.vue')['default']
  }
}
