/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: (typeof import('./components/AppFooter.vue'))['default']
    AppTopBar: (typeof import('./components/AppTopBar.vue'))['default']
    DBtn: typeof import('vue-devui/btn/index.es.js')['Btn']
    DButton: typeof import('vue-devui/button/index.es.js')['Button']
    DCodeEditor: (typeof import('vue-devui/code-editor/index.es.js'))['CodeEditor']
    DCol: typeof import('vue-devui/grid/index.es.js')['Col']
    DRow: typeof import('vue-devui/grid/index.es.js')['Row']
    DStatus: typeof import('vue-devui/status/index.es.js')['Status']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElText: typeof import('element-plus/es')['ElText']
    ExamStatus: typeof import('./components/ExamStatus.vue')['default']
    GgbPlayer: (typeof import('./components/GgbPlayer.vue'))['default']
    ReadmeRender: (typeof import('./components/ReadmeRender.vue'))['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SubjectInfo: typeof import('./components/SubjectInfo.vue')['default']
    SvgIcon: typeof import('./components/SvgIcon.vue')['default']
  }
}
